version: '3.2'

services:
  mysql:
    image: 'mysql:5'
    command: --default-authentication-plugin=mysql_native_password --lower_case_table_names=1
    ports:
      - '33006:3306'
    volumes:
      - '~/mnt/mysql/:/var/lib/mysql/'
    environment:
      - MYSQL_ROOT_PASSWORD=mysql
      - MYSQL_DATABASE=fitech
      - MYSQL_USER=test
      - MYSQL_PASSWORD=test
  redis:
    image: 'redis:latest'
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    ports:
      - '6379:6379'